export default {
  SET_ACTIVE_FILTER: `SET_ACTIVE_FILTER`,
  INCREMENT_SHOWED_FILM_COUNT: `INCREMENT_SHOWED_FILM_COUNT`,
  RESET_SHOWED_FILM_COUNT: `RESET_SHOWED_FILM_COUNT`,
  SET_ERROR_MESSAGE: `SET_ERROR_MESSAGE`,
};
